services:
    SmtLab\JsonApiBundle\JsonApiServer:
        class: SmtLab\JsonApiBundle\JsonApiServer
        arguments: ['@doctrine.orm.entity_manager']
    SmtLab\JsonApiBundle\Controller\JsonApiController:
        class: SmtLab\JsonApiBundle\Controller\JsonApiController
        tags: ['controller.service_arguments']
